# Generated by Django 5.0.1 on 2024-01-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('명칭', models.CharField(max_length=100)),
                ('개요', models.TextField()),
                ('weighted_평점', models.FloatField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
